name: create_build

on:
  push:
    branches: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Experiment
      run: |
        cd pathfinder
        npm install
        npm run build
