# name: create_build

# on:
#   push:
#     branches: 'main'

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:

#     - name: Build
#       run: |
#         npm install
#         npm run build
